### ISSUE TITLE
Doesn't work when supplying multiple genomes

### ISSUE THREAD

**Issue by adityabandla** [alexcritschristoph/RPxSuite#4]
I get an error when trying to use RPxSuite with multiple genomes
```
RPxSuite.py -g Ribosomal_L6 *.fasta
RPxSuite.py: error: unrecognized arguments: 1NBY2EDSCC.76.contigs.filtered.fasta 1NBY2EDSMT.2.contigs.filtered.fasta
```

**Comment by alexcritschristoph** [comment]
Thank you for finding this! We've usually been concatenating genomes together into one fasta file to run on so haven't noticed. Fixed by #5
