### ISSUE TITLE
scaling gene calling

### ISSUE THREAD

**Issue by adityabandla** [alexcritschristoph/RPxSuite#6]
Running prodigal for large sets of assemblies is limiting due to it being run on a single core
Can this be parallelised  say using GNU parallel?

Also, it would be great if the user can supply protein fasta files instead

**Comment by alexcritschristoph** [comment]
Hi Aditya, 
I just pushed a commit allowing you to specify a prodigal genes file, either genes or proteins - just make sure you also match `--amino_acid` depending on which you are doing. Let me know if it causes you any issues.
Thanks,
Alex
