### ISSUE TITLE
Mapping reads to species groups

### ISSUE THREAD

**Issue by adityabandla** [alexcritschristoph/RPxSuite#9]
@alexcritschristoph After running RPxSuite for a given gene of interest, what is the recommended % identity to map reads onto them? For example, species groups using ribosomal protein S9 are defined by clustering them at 97.2 % identity. Thus, when mapping sample reads onto these, I would assume its the same % identity that one should use i.e. 97.2 % in this case?

**Comment by MrOlm** [comment]
I would make it looser to accommodate the fact that there's random fluctuations in how many mis-matches each individual gene will have (see the third figure here https://instrain.readthedocs.io/en/latest/Advanced_use.html for some simulated data showing this)

-Matt

**Comment by adityabandla** [comment]
@MrOlm Thanks for the explanation & the link to it, was very helpful. When clustering genes at say 97.2 % identity and trying to recruit reads to this centroid, is it correct to say that the expected difference in ANI between reads & the reference gene is 97.2 %, however setting this at say 94 - 95 %  is better given how reads are recruited to different parts of the reference based on SNP's, also ensures that the expected coverage breadth is achieved

**Comment by MrOlm** [comment]
Yes, exactly! I would go with 94-95%  read ANI when mapping to 97.2 % identity centroids.

Best,
Matt
